"""Add device_status_history table

Revision ID: c2bbf559dfff
Revises: 
Create Date: 2025-07-16 22:18:31.607665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bbf559dfff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_status_history_device_id'), 'device_status_history', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_status_history_id'), 'device_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_status_history_id'), table_name='device_status_history')
    op.drop_index(op.f('ix_device_status_history_device_id'), table_name='device_status_history')
    op.drop_table('device_status_history')
    # ### end Alembic commands ###
